name: 'Build for PR, upload asset'

on:
  pull_request:
    types: [review_requested]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: install app dependencies
        run: |
          npm ci
      - name: Build
        shell: pwsh
        continue-on-error: true
        run: |
          npm run tauri build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: UCP3-GUI.zip
          path: src-tauri/target/release/UCP3-GUI.exe
