name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run package
          
      - name: Make zip
        shell: pwsh
        run: |
          pushd release\build\win-unpacked
          7z a -tzip -m0=Copy ..\..\..\UCP3-GUI-portable-latest.zip *
          popd
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            UCP3-GUI-portable-latest.zip
            release/build/*.exe

      - name: Upload exe artifact
        uses: actions/upload-artifact@v2
        with:
          name: UCP3-GUI-installer
          path: release/build/*.exe

      - name: Upload portable artifact
        uses: actions/upload-artifact@v2
        with:
          name: UCP3-GUI-portable
          path: release/build/win-unpacked/*
